### ISSUE TITLE
Cannot play when selecting theme, cannot unselect theme (no Scroll Lock key)

### ISSUE THREAD

**Issue by Iiridayn** [DivinElegy/GrooveNights#48]
When I select this theme from the themes available, I get a screen which states:

> The initial screen set by this theme is not valid. It is not defined anywhere in the theme or in the _fallback theme. This is an error in the theme and should be reported to the theme's author. You can press Scroll Lock (the operator key) to access the service menu and change to a different theme.

My package manager reports Stepmania 5.0.11 is installed, which should be up to date. I've tried all three branches of this repository, but none work, and I've not had much luck finding this issue or any documentation via Google. What can I do to help?

**Comment by ghost** [comment]
Sorry, this theme was designed for OpenITG (which is based on a very old version of StepMania). Typically themes designed for older versions of StepMania don't work on newer versions due to API changes.

Since you mentioned a package manager, I assume you're on Linux. You can get a precompiled Linux binary for OpenITG [here](http://openitg.gr-p.com/full-linux/OpenITG%20beta%202%20linux.zip) or the source is available [here](https://github.com/openitg/openitg)

**Comment by Iiridayn** [comment]
Ah, thank you :). That explains very well why it wasn't working :).
